// Stub auto-generated by Xcode — replaced by `BudgetLiveActivity.swift`.
// Kept as an empty file because the bundle template referenced its symbol;
// safe to delete entirely once you confirm the build is green.

import Foundation
