import Foundation

// ============================================================
// MARK: - Action Card Model
// ============================================================
// Represents a single prioritized action on the dashboard.
// Generated by ActionCardEngine from all 4 engine snapshots.
// ============================================================

struct ActionCard: Identifiable, Hashable {
    let id: String                     // deterministic ID for dismiss tracking
    let type: ActionCardType
    let priority: ActionPriority
    let title: String
    let subtitle: String
    let icon: String                   // SF Symbol
    let iconColor: Int                 // hex color for icon background
    let deepLink: ActionDeepLink
}

enum ActionCardType: String, Hashable {
    case forecastRisk                  // spending pace too high
    case overBudget                    // over monthly budget
    case duplicateTransactions         // review duplicates
    case uncategorized                 // uncategorized transactions
    case unusedSubscriptions           // cancel unused subs
    case billDue                       // upcoming bill
    case overdueBill                   // overdue bill
    case settlementNeeded              // household balance unsettled
    case categoryCap                   // category budget near/exceeded
    case reviewQueue                   // general review items
    case goalBehind                    // goal falling behind pace
}

enum ActionPriority: Int, Comparable, Hashable {
    case critical = 0                  // immediate attention
    case high = 1                      // important
    case medium = 2                    // helpful
    case low = 3                       // informational

    static func < (lhs: ActionPriority, rhs: ActionPriority) -> Bool {
        lhs.rawValue < rhs.rawValue
    }
}

enum ActionDeepLink: Hashable {
    case forecast
    case review
    case subscriptions
    case household
    case goals
    case budget
    case transactions
}
